name: pond_care
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: ff59917a7ca9c0648e0f5bc3a8ac0245f005c9d3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/generated/

  fonts:
      - family: Baby Bears
        fonts:
          - asset: assets/fonts/Baby-Bears.ttf
      - family: Araside
        fonts:
          - asset: assets/fonts/Araside.ttf
