name: pond_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/

  fonts:
      - family: satoshi
        fonts:
          - asset: assets/fonts/satoshi-regular.otf
            weight: 400
          - asset: assets/fonts/satoshi-medium.otf
            weight: 500
      - family: avenir
        fonts:
          - asset: assets/fonts/avenir-bold.ttf
            weight: 700
          - asset: assets/fonts/avenir-normal.ttf
            weight: 500

